ChangJin-Lee/algorithm-study

Week001/Santa/bj_10988_팰린드롬인지확인하기.cpp, Week001/Santa/bj_1193_분수찾기.cpp, Week001/Santa/bj_1316_그룹단어체커.cpp, Week001/Santa/bj_2444_별찍기-7.cpp, Week001/Santa/bj_3003_킹퀸룩비숍나이트폰.cpp
update: bj_10988_팰린드롬인지확인하기
update: bj_1193_분수찾기
update: bj_1316_그룹단어체커
update: bj_2444_별찍기-7
update: bj_3003_킹퀸비숍나이트폰
=> Week001_Santa

Week001/Noah/bj_10103_주사위게임.cpp, Week001/Noah/bj_1546_평균.cpp, Week001/Noah/bj_2739_구구단.cpp, Week001/Noah/bj_2884_알람시계.cpp, Week001/Noah/bj_4766_일반화학실험.cpp
bj_1546_평균
bj_2739_구구단
bj_2884_알람시계
bj_4766_일반화학실험
bj_10103_주사위게임
=> Week001_Noah

Week002/CJ/bj_10870_피보나치수5.cpp, Week002/CJ/bj_11729_하노이탑이동순서.cpp, Week002/CJ/bj_1181_단어정렬.cpp, Week002/CJ/bj_25501_재귀의귀재.cpp, Week002/README.md
Week002 CJ 
업데이트 합니다!
|제목|구분|url|
|백준 1181 단어정렬|문자열|https://www.acmicpc.net/problem/1181|
|백준 10798 세로읽기|문자열|https://www.acmicpc.net/problem/10798|
|백준 10870 피보나치수5|재귀|https://www.acmicpc.net/problem/10870|
|백준 11729 하노이탑이동순서|재귀|https://www.acmicpc.net/problem/11729|
|백준 25501 재귀의귀재|재귀,문자열|https://www.acmicpc.net/problem/25501|
=> Week002 CJ

Week003/README.md, Week003/Santa/bj_1021_회전하는큐.cpp, Week003/Santa/bj_10773_제로.cpp, Week003/Santa/bj_11866_요세푸스문제0.cpp, Week003/Santa/bj_2164_카드2.cpp, Week003/Santa/bj_2346_풍선터뜨리기.cpp
|제목|구분|url|
|백준 1021 회전하는큐|덱|https://www.acmicpc.net/problem/1021|
|백준 2164 카드2|큐|https://www.acmicpc.net/problem/2164|
|백준 2346 풍선터뜨리기|덱|https://www.acmicpc.net/problem/2346|
|백준 10773 제로|스택|https://www.acmicpc.net/problem/10773|
|백준 11866 요세푸스문제0|큐|https://www.acmicpc.net/problem/11866|
=> Week003 Santa

Week002/Noah/bj_11656_접미사배열.cpp, Week003/Noah/bj_13335_트럭.cpp, Week003/Noah/bj_1874_스택수열.cpp, Week003/Noah/bj_1966_프린터큐.cpp, Week003/Noah/bj_2493_탑.cpp, Week003/Noah/bj_5430_AC.cpp
| 백준 1874 스택수열 | 스택 | https://www.acmicpc.net/problem/1874 |
| 백준 1966 프린터큐 | 큐 | https://www.acmicpc.net/problem/1966 |
| 백준 2493 탑 | 스택 | https://www.acmicpc.net/problem/2493 |
| 백준 5430 AC | 덱 | https://www.acmicpc.net/problem/5430 |
| 백준 13335 트럭 | 큐 | https://www.acmicpc.net/problem/13335 |
=> Week003 Noah

Week004/CJ/bj_1406_에디터.cpp, Week004/CJ/bj_2983_개구리공주.cpp, Week004/CJ/bj_30885_Φ².cpp, Week004/CJ/bj_5397_키로거.cpp, Week004/README.md
|제목|구분|url|
|백준 1406 에디터|연결리스트|https://www.acmicpc.net/problem/1406|
|백준 2983 개구리공주|연결리스트|https://www.acmicpc.net/problem/2983|
|백준 5397 키로거|연결리스트|https://www.acmicpc.net/problem/5397|
|백준 30885 Φ²|연결리스트|https://www.acmicpc.net/problem/30885|
=> Week004 Cj

Week004/Noah/bj_1406_에디터.cpp, Week004/Noah/bj_5379_키로거.cpp
|제목|구분|url|
|백준 1406 에디터|연결리스트|https://www.acmicpc.net/problem/1406|
|백준 5397 키로거|연결리스트|https://www.acmicpc.net/problem/5397|
30885는 아직 도전중입니다..
=> Week004 Noah

Week005/CJ/bj_1167_트리의지름.cpp, Week005/CJ/bj_11724_연결요소의개수.cpp, Week005/CJ/bj_16404_주식회사승범이네.cpp, Week005/CJ/bj_1991_트리순회.cpp, Week005/CJ/bj_3584_가장가까운공통조상.cpp, Week005/README.md
|제목|구분|url|
|백준 1991 트리순회|트리|https://www.acmicpc.net/problem/1991|
|백준 16404 주식회사승범이네|트리,힙|https://www.acmicpc.net/problem/16404|
|백준 3584 가장가까운공통조상|트리|https://www.acmicpc.net/problem/3584|
|백준 1167 트리의지름|트리,힙|https://www.acmicpc.net/problem/1167|
|백준 16404 연결요소의개수|트리|https://www.acmicpc.net/problem/16404|
=> Week005 CJ

Week005/Noah/bj_11725_트리의부모찾기.cpp, Week005/Noah/bj_1240_노드사이의거리.cpp, Week005/Noah/bj_1991_트리순회.cpp, Week005/README.md
|제목|구분|url|
|백준 1240 노드 사이의 거리|트리|https://www.acmicpc.net/problem/1240|
|백준 1991 트리순회|트리|https://www.acmicpc.net/problem/1991|
|백준 11725 트리의 부모 찾기|트리|https://www.acmicpc.net/problem/11725|
=> Week005 Noah

Week007/CJ/bj_10026_적록색약.cpp, Week007/CJ/bj_1300_k번째수.cpp, Week007/CJ/bj_14921_용액합성하기.cpp, Week007/CJ/bj_2606_바이러스.cpp, Week007/CJ/bj_7576_토마토.cpp
7주차 풀리퀘입니다!
|제목|구분|url|
|백준 1300 k번째 수|이분탐색|https://www.acmicpc.net/problem/1300|
|백준 14921 용액합성하기|이분탐색|https://www.acmicpc.net/problem/14921|
|백준 10026 적록색약|BFS,DFS|https://www.acmicpc.net/problem/10026|
|백준 7576 토마토|BFS,DFS|https://www.acmicpc.net/problem/7576|
|백준 2606 바이러스|BFS,DFS|https://www.acmicpc.net/problem/2606|
=> Week007 CJ

Week007/README.md, Week007/Santa/bj_14716_현수막.cpp
통촉하여주시옵소서..
git 관리는 제대로 하겠습니다.. 
죄송합니다.. 
문제는 이분탐색 풀다가 시간을 몾맞춰서.. 
다음번까지 풀어오겠습니다! 
<br>
|제목|구분|url|
|백준 14716 현수막|BFS,DFS|https://www.acmicpc.net/problem/14716|
=> Week007 Santa

Week020/CJ/hackerrank_ClimbingtheLeaderboard.cpp, Week020/CJ/hackerrank_ExtraLongFactorials.cpp, Week020/CJ/hackerrank_FormingaMagicSquare.cpp, Week020/README.md
|제목|구분|url|
|hackerrank_FormingaMagicSquare.cpp|구현|https://www.hackerrank.com/challenges/magic-square-forming/problem?isFullScreen=true|
|hackerrank_ClimbingtheLeaderboard.cpp|이분탐색, 구현|https://www.hackerrank.com/challenges/climbing-the-leaderboard/problem?isFullScreen=true|
|hackerrank_ExtraLongFactorials.cpp|큰수곱셈, 구현|https://www.hackerrank.com/challenges/extra-long-factorials/problem?isFullScreen=true|
=> Week020 CJ

Week021/README.md, Week021/Santa/hackerrank_CommonChild.cpp, Week021/Santa/programmers_입국심사.cpp, Week021/Santa/programmers_표현가능한이진트리.cpp
|제목|구분|url|
|프로그래머스 입국 심사|이분탐색|https://school.programmers.co.kr/learn/courses/30/lessons/43238|
|프로그래머스 표현 가능한 이진트리|트리|https://school.programmers.co.kr/learn/courses/30/lessons/150367|
|HackerRank CommonChild|LCS|https://www.hackerrank.com/challenges/common-child/problem?isFullScreen=true|
=> Week021 Santa

Week021/Noah/leetcode_1190_ReverseSubstrings.cpp, Week021/Noah/leetcode_2196_CreateBinaryTree.cpp, Week021/Noah/programmers_nqeen.cpp, Week021/README.md
|leetcode_Reverse Substrings Between Each Pair of Parentheses|구현|https://leetcode.com/problems/reverse-substrings-between-each-pair-of-parentheses/|
|leetcode_Create Binary Tree From Descriptions|트리, 해시|https://leetcode.com/problems/create-binary-tree-from-descriptions|
|programmers N-Queen|dfs, 백트래킹|https://school.programmers.co.kr/learn/courses/30/lessons/12952|
=> Week021 Noah

Week022/README.md, Week022/Santa/programmers_디스크컨트롤러.cpp, Week022/Santa/programmers_베스트앨범.cpp, Week022/Santa/programmers_불량사용자.cpp
|제목|구분|url|
|프로그래머스 베스트 앨범|해시|https://school.programmers.co.kr/learn/courses/30/lessons/42579|
|프로그래머스 불량 사용자|순열|https://school.programmers.co.kr/learn/courses/30/lessons/64064|
|프로그래머스 디스크 컨트롤러|우선순위 큐|https://school.programmers.co.kr/learn/courses/30/lessons/42627|
=> Week022 Santa

Week022/Noah/programmers_괄호변환.cpp, Week022/Noah/programmers_두큐합같게만들기.cpp, Week022/Noah/programmers_여행경로.cpp, Week022/README.md
|programmers_여행경로|BFS, DFS|https://school.programmers.co.kr/learn/courses/30/lessons/43164|
|programmers_괄호변환|스택, 구현|https://school.programmers.co.kr/learn/courses/30/lessons/60058|
|programmers_두 큐 합 같게 만들기|큐, 구현, 투포인터|https://school.programmers.co.kr/learn/courses/30/lessons/118667|
=> Week022 Noah

Week023/CJ/hackerrank_AttributeParser.cpp, Week023/CJ/hackerrank_JackgoestoRapture.cpp, Week023/CJ/programmers_부대복귀.cpp, Week023/README.md
|제목|구분|url|
|programmers_부대복귀|bfs|https://school.programmers.co.kr/learn/courses/30/lessons/132266|
|hackerrank_JackgoestoRapture|Graph|https://www.hackerrank.com/challenges/jack-goes-to-rapture/problem|
|hackerrank_AttributeParser|string|https://www.hackerrank.com/challenges/attribute-parser/problem|
=> Week023 CJ

Week023/README.md, Week023/Santa/programmers_야근지수.cpp, Week023/Santa/programmers_이중우선순위큐.cpp, Week023/Santa/programmers_호텔방배정.cpp
|제목|구분|url|
|프로그래머스 이중우선순위큐|힙|https://school.programmers.co.kr/learn/courses/30/lessons/42628|
|프로그래머스 호텔 방 배정|해시|https://school.programmers.co.kr/learn/courses/30/lessons/64063|  
|프로그래머스 야근 지수|우선순위큐|https://school.programmers.co.kr/learn/courses/30/lessons/12927|
=> Week023 Santa

Week023/Noah/leetcode_986_IntervalListIntersections.cpp, Week023/Noah/programmers_방금그곡.cpp, Week023/Noah/programmers_압축.cpp, Week023/README.md
|programmers_압축|구현, 해시, 문자열|https://school.programmers.co.kr/learn/courses/30/lessons/17684|
|programmers_방금그곡|구현, 문자열|https://school.programmers.co.kr/learn/courses/30/lessons/17683|
|leetcode_986_IntervalListIntersections|투포인터|https://leetcode.com/problems/interval-list-intersections/|
=> Week023 Noah

Week024/README.md, Week024/Santa/programmers_단어변환.cpp, Week024/Santa/programmers_등대.cpp, Week024/Santa/programmers_카운트다운.cpp
|제목|구분|url|
|프로그래머스 등대|DFS|https://school.programmers.co.kr/learn/courses/30/lessons/133500|
|프로그래머스 단어 변환|BFS|https://school.programmers.co.kr/learn/courses/30/lessons/43163|
|프로그래머스 카운트다운|DP|https://school.programmers.co.kr/learn/courses/30/lessons/131129|
=> Week024 Santa

Week024/Noah/leetcode_1653_MinimumDeletions.cpp, Week024/Noah/programmers_멀쩡한사각형.cpp, Week024/Noah/programmers_파괴되지않은건물.cpp, Week024/README.md
|programmers_멀쩡한사각형|구현, 수학|https://school.programmers.co.kr/learn/courses/30/lessons/62048|
|leetcode_1653_Minimum Deletions to Make String Balanced|DP|https://leetcode.com/problems/minimum-deletions-to-make-string-balanced|
|programmers_파괴되지않은건물|누적합|https://school.programmers.co.kr/learn/courses/30/lessons/92344|
=> Week024 Noah

Week024/CJ/hackerrank_CountLuck.cpp, Week024/CJ/hackerrank_CuttheTree.cpp, Week024/CJ/hackerrank_KnightLonaChessboard.cpp, Week024/README.md, Week024/Santa/programmers_단어변환.cpp, Week024/Santa/programmers_등대.cpp, Week024/Santa/programmers_카운트다운.cpp
|제목|구분|url|
|hackerrank Count Luck|BFS|https://www.hackerrank.com/challenges/count-luck/problem?isFullScreen=true|
|hackerrank Cut the Tree|DFS|https://www.hackerrank.com/challenges/cut-the-tree/problem?isFullScreen=true|
|hackerrank KnightL on a Chessboard|BFS|https://www.hackerrank.com/challenges/knightl-on-chessboard/problem?isFullScreen=true|
=> Week024 CJ

Week025/README.md, Week025/leetcode_Brick_wall.cpp, Week025/programmers_거스름돈.cpp, Week025/programmers_예상대진표.cpp
|제목|구분|url|
|leetcode Brick-wall|해시맵|https://leetcode.com/problems/brick-wall/description/|
|프로그래머스 예상 대진표|구현|https://school.programmers.co.kr/learn/courses/30/lessons/12985|
|프로그래머스 거스름돈|DP|https://school.programmers.co.kr/learn/courses/30/lessons/12907|
=> Week025 Santa

Week025/CJ/hackerrank_Encryption.cpp, Week025/CJ/hackerrank_Journeytothemoon.cpp, Week025/CJ/hackerrank_인사고과.cpp, Week025/CJ/programmers_인사고과.cpp, Week025/README.md, Week025/leetcode_Brick_wall.cpp, Week025/programmers_거스름돈.cpp, Week025/programmers_예상대진표.cpp
|제목|구분|url|
|hackerrank_Encryption|구현|https://www.hackerrank.com/challenges/encryption/problem|
|programmers_인사고과|sorting|https://school.programmers.co.kr/learn/courses/30/lessons/152995|
|hackerrank_Journeytothemoon|그래프|https://www.hackerrank.com/challenges/journey-to-the-moon/problem|
=> Week025 CJ
